### ISSUE TITLE
invalid memory

### ISSUE THREAD

**Issue by tommoholmes10** [PuerkitoBio/gocrawl#40]
when I run my gocrawler, but suddenly it's stop. and I get message
``panic: runtime error: invalid memory address or nil pointer dereference``
how I fix it

**Comment by miko-code** [comment]
I guess you are doing something wrong ... 
Can you post your code

**Comment by tommoholmes10** [comment]
```go
func scraper(docs *goquery.Document) {
  var data interface{}
      docs.Find(".menu_tree .submenu a").Each(func(i int, s *goquery.Selection) {
        base, _ := s.Attr("href")
        fmt.Println("link", base)
        dok, _ := goquery.NewDocument(base)
        counts, _ := dok.Find(".pagination:nth-child(1) a:nth-child(6)").Attr("href")
        counts = path.Base(counts)
        count, _ := strconv.Atoi(counts)
        for i := 1; i < count; i++ {
          bases := base+"/"
          no := strconv.Itoa(i)
          bases   = bases+no
          doc, _ := goquery.NewDocument(bases) 
            doc.Find(".product-thumb li").Each(func(i int, s *goquery.Selection) {
              links, _ := s.Find("a").Attr("href")
              image, _ := s.Find("img").Attr("src")
              u, _ := url.Parse(image)
              imagenormal := purell.NormalizeURL(u, purell.FlagsUsuallySafeGreedy|purell.FlagRemoveDuplicateSlashes|purell.FlagRemoveFragment)
              price  := strings.TrimSpace(s.Find(".price").Text())
              price = strings.TrimSpace(strings.Replace(price, "Rp", "", -1))
              price = strings.TrimSpace(strings.Replace(price, ".", "", -1))
              prices, _ := strconv.Atoi(price)
              title :=  strings.TrimSpace(s.Find("h3").Text())
              docs, _ := goquery.NewDocument(bases) 
              var desc string
              var icon string
              docs.Find("meta").Each(func(i int, s *goquery.Selection) {
                if descs, _ := s.Attr("name"); strings.EqualFold(descs, "description") {
                  desc, _ = s.Attr("content")
                  desc = strings.TrimSpace(desc)
                }
              })
              docs.Find("link").Each(func(i int, s *goquery.Selection) {
                if icons, _ := s.Attr("rel"); strings.EqualFold(icons, "shortcut icon") {
                  icon, _ = s.Attr("href")
                }
              })
              data = Product{Image: imagenormal, Title: title, Price: prices, Desc: desc, Brand : "-", Site : "marketnesia", Icon : icon, Link : links}
               client.Index().
                Index("witch").
                Type("product").
                BodyJson(data).
                Do()
                client.Flush().Index("witch").Do()
            })
        }
    })
}

```

**Comment by tommoholmes10** [comment]
Hai I'm still get panic: runtime error: invalid memory address or nil pointer dereference. How I fix it.. My code is 
```go
func scraper(docs *goquery.Document) {
      defer func() {
        if r := recover(); r != nil {
            fmt.Println("Recovered in f", r)
        }
    }()
  var data interface{}
      docs.Find(".menu_tree .submenu a").Each(func(i int, s *goquery.Selection) {
        base, _ := s.Attr("href")
        fmt.Println("link", base)
        dok, _ := goquery.NewDocument(base)
        counts, _ := dok.Find(".pagination:nth-child(1) a:nth-child(6)").Attr("href")
        counts = path.Base(counts)
        count, _ := strconv.Atoi(counts)
        for i := 1; i < count; i++ {
          bases := base+"/"
          no := strconv.Itoa(i)
          bases   = bases+no
          doc, _ := goquery.NewDocument(bases) 
            doc.Find(".product-thumb li").Each(func(i int, s *goquery.Selection) {
              links, _ := s.Find("a").Attr("href")
              image, _ := s.Find("img").Attr("src")
              u, _ := url.Parse(image)
              imagenormal := purell.NormalizeURL(u, purell.FlagsUsuallySafeGreedy|purell.FlagRemoveDuplicateSlashes|purell.FlagRemoveFragment)
              price  := strings.TrimSpace(s.Find(".price").Text())
              price = strings.TrimSpace(strings.Replace(price, "Rp", "", -1))
              price = strings.TrimSpace(strings.Replace(price, ".", "", -1))
              prices, _ := strconv.Atoi(price)
              title :=  strings.TrimSpace(s.Find("h3").Text())
              docs, _ := goquery.NewDocument(bases) 
              var desc string
              var icon string
              docs.Find("meta").Each(func(i int, s *goquery.Selection) {
                if descs, _ := s.Attr("name"); strings.EqualFold(descs, "description") {
                  desc, _ = s.Attr("content")
                  desc = strings.TrimSpace(desc)
                }
              })
              docs.Find("link").Each(func(i int, s *goquery.Selection) {
                if icons, _ := s.Attr("rel"); strings.EqualFold(icons, "shortcut icon") {
                  icon, _ = s.Attr("href")
                }
              })
              data = Product{Image: imagenormal, Title: title, Price: prices, Desc: desc, Brand : "-", Site : "marketnesia", Icon : icon, Link : links}
               client.Index().
                Index("witch").
                Type("product").
                BodyJson(data).
                Do()
                client.Flush().Index("witch").Do()
            })
        }
    })
}
```

**Comment by PuerkitoBio** [comment]
The panic should tell you where it occurred, try to debug it and send the minimal code required to reproduce the problem if it looks like it's a bug in gocrawl. As I asked you in another issue, please look at https://github.com/golang/go/wiki/HowToAsk for how to ask a good, specific question, and keep in mind that this is the issue tracker for gocrawl, not a place to ask for debugging help on a personal project. Also note that you ignore just about every error in your code, which can lead to a panic.

**Comment by avelino** [comment]
@PuerkitoBio example return error

```
doc, err := goquery.NewDocument("https://gist.githubusercontent.com/avelino/a4a8527f76d7eb14b2acb1e761c69b30/raw/98b1040bd1b5a09287b378f0327c37449ba0f5f5/test.html")
if err != nil {
    log.Println(err)
}
val, _ := doc.Find("meta[name=\"twitter:image\"]").Attr("content")
```
Error:
```
2016/04/30 03:48:40 unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x59657f]

goroutine 1 [running]:
panic(0x8f9ca0, 0xc82000e260)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
shelfgit.com/poorny/spider/providers/feeds.UnmarshalXML(0xc82013c150, 0x2c, 0xc82013c2d0, 0x29, 0xc82008c5a0, 0x118, 0x0, 0x0, 0x0, 0x0, ...)
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/providers/feeds/feeds.go:74 +0x5af
shelfgit.com/poorny/spider/providers.FeedByBot()
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/providers/providers.go:173 +0xf35
shelfgit.com/poorny/spider/providers.Switch(0xc82000a5d0, 0x1, 0x1)
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/providers/providers.go:107 +0x1466
main.main.func1(0xc820138000)
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/main.go:22 +0x103
github.com/codegangsta/cli.(*App).Run(0xc820134000, 0xc82000a5c0, 0x2, 0x2, 0x0, 0x0)
        /home/avelino/projects/go/src/github.com/codegangsta/cli/app.go:163 +0xbfc
main.main()
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/main.go:25 +0x163
exit status 2
```
